# Generated by Django 5.2.5 on 2026-07-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_rut',
            field=models.CharField(blank=True, default='', help_text='RUT con formato 12.345.678-K', max_length=20),
        ),
    ]
