# Generated by Django 5.2.5 on 2026-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_is_refunded_order_refund_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección cifrada en reposo', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(help_text='Teléfono cifrado en reposo', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_rut',
            field=models.CharField(blank=True, default='', help_text='RUT cifrado en reposo', max_length=255),
        ),
    ]
