# Generated by Django 5.2.5 on 2026-07-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_adminuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='full_name',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='commune',
            field=models.CharField(default='Santiago', max_length=100),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='country',
            field=models.CharField(default='Chile', max_length=50),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='first_name',
            field=models.CharField(default='Lina', max_length=50),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='last_name_maternal',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='last_name_paternal',
            field=models.CharField(default='Propietaria', max_length=50),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='region',
            field=models.CharField(default='Región Metropolitana de Santiago', max_length=100),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='rut_body',
            field=models.CharField(default='11111111', max_length=10),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='rut_dv',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
