# Generated by Django 5.2.5 on 2026-08-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_adminuser_full_name_adminuser_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='commune',
            new_name='city',
        ),
    ]
