# Generated by Django 5.2.5 on 2026-08-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_adminuser_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(default='Administración', max_length=150)),
                ('changes_summary', models.TextField(help_text='Resumen de parámetros modificados')),
                ('previous_config', models.JSONField(default=dict)),
                ('new_config', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
