# Generated by Django 5.2.5 on 2026-08-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_confighistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
