# Generated by Django 5.2.5 on 2026-08-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_adminuser_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessconfig',
            name='value',
            field=models.TextField(),
        ),
    ]
