# Generated by Django 5.2.5 on 2026-08-28 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sitevisit_visitlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='total_uniques',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='total_visits',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Cliente', help_text='Primer y segundo nombre del cliente', max_length=75)),
                ('last_name_paternal', models.CharField(default='Registrado', help_text='Apellido paterno del cliente', max_length=75)),
                ('last_name_maternal', models.CharField(blank=True, default='', help_text='Apellido materno del cliente', max_length=75, null=True)),
                ('rut_body', models.CharField(blank=True, default='', help_text='Cuerpo numérico del RUT cifrado en reposo', max_length=255, null=True)),
                ('rut_dv', models.CharField(blank=True, default='', help_text='Dígito verificador del RUT (0-9, K)', max_length=10, null=True)),
                ('email', models.EmailField(help_text='Correo electrónico único del cliente', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', help_text='Teléfono cifrado en reposo', max_length=255, null=True)),
                ('country', models.CharField(default='Chile', max_length=50)),
                ('region', models.CharField(default='Región Metropolitana de Santiago', max_length=100)),
                ('city', models.CharField(default='Santiago', max_length=100)),
                ('address', models.CharField(blank=True, default='', help_text='Calle, número, dpto cifrado en reposo', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='api.commune')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.client'),
        ),
    ]
